### ISSUE TITLE
How to build this example?

### ISSUE THREAD

**Issue by eiswind** [klibio/example.bnd.rcp#1]
Hi I'd like to know the steps for bulding this example. Simply doing gradle build does not seem to do the trick.

Any help would be appreciated,

**Comment by gamerson** [comment]
I was able to make a few changes here: https://github.com/peterkir/example.bnd.rcp/pull/3

But it seems there is still more work to do for others to build.  Maybe @peterkir  can comment.  I know that you can at least build and execute the `example.rcp.headless` project by doing ```$ cd example.rcp.headless
$ gradlew export
$ java -jar generated/distributions/executable/headless.jar
```

**Comment by TheECanyon** [comment]
Please refer to the new Wiki [How to build](https://github.com/klibio/example.bnd.rcp/wiki/How-to-build)
